const LOCATION_TYPES = {
    NONE: "NONE",
    CHARACTER_CREATOR: "CHARACTER_CREATOR",
    FREEROAM: "FREEROAM",
    LOBBY: "LOBBY",
    ARENA: "ARENA",
    GANG_WAR: "GANG_WAR",
    DUEL: "DUEL"
}
module.exports = LOCATION_TYPES;