// <auto-generated />
using System;
using LSDM.Infrastracture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LSDM.Infrastracture.Migrations
{
    [DbContext(typeof(LSDMDbContext))]
    [Migration("20260419223455_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LSDM.Domain.Entities.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BannedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BannedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.BanIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BanId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.ToTable("BanIdentifiers");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.FaceFeature", b =>
                {
                    b.Property<int>("OutfitId")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<float>("Scale")
                        .HasColumnType("real");

                    b.HasKey("OutfitId", "Index");

                    b.ToTable("FaceFeatures");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.HeadBlend", b =>
                {
                    b.Property<int>("OutfitId")
                        .HasColumnType("integer");

                    b.Property<int>("ShapeFirstId")
                        .HasColumnType("integer");

                    b.Property<float>("ShapeMix")
                        .HasColumnType("real");

                    b.Property<int>("ShapeSecondId")
                        .HasColumnType("integer");

                    b.Property<int>("SkinFirstId")
                        .HasColumnType("integer");

                    b.Property<float>("SkinMix")
                        .HasColumnType("real");

                    b.Property<int>("SkinSecondId")
                        .HasColumnType("integer");

                    b.HasKey("OutfitId");

                    b.ToTable("HeadBlends");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.HeadOverlay", b =>
                {
                    b.Property<int>("OutfitId")
                        .HasColumnType("integer");

                    b.Property<int>("HeadOverlayId")
                        .HasColumnType("integer");

                    b.Property<int>("FirstColor")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<float>("Opacity")
                        .HasColumnType("real");

                    b.HasKey("OutfitId", "HeadOverlayId");

                    b.ToTable("HeadOverlays");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.LSDMUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("LastHwid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastIpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSocialClubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<int>("ServerRoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ServerRoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LSDM.Domain.Entities.Outfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EyeColor")
                        .HasColumnType("integer");

                    b.Property<int>("HairColor")
                        .HasColumnType("integer");

                    b.Property<int>("Model")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.OutfitComponent", b =>
                {
                    b.Property<int>("OutfitId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("Drawable")
                        .HasColumnType("integer");

                    b.Property<int>("Texture")
                        .HasColumnType("integer");

                    b.HasKey("OutfitId", "ComponentId");

                    b.ToTable("OutfitComponents");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.OutfitProp", b =>
                {
                    b.Property<int>("OutfitId")
                        .HasColumnType("integer");

                    b.Property<int>("PropId")
                        .HasColumnType("integer");

                    b.Property<int>("Drawable")
                        .HasColumnType("integer");

                    b.Property<int>("Texture")
                        .HasColumnType("integer");

                    b.HasKey("OutfitId", "PropId");

                    b.ToTable("OutfitProps");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.ServerRole", b =>
                {
                    b.Property<int>("ServerRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServerRoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ServerRoleId");

                    b.ToTable("ServerRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LSDM.Domain.Entities.Ban", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.LSDMUser", "BannedByUser")
                        .WithMany("AssignedBans")
                        .HasForeignKey("BannedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LSDM.Domain.Entities.LSDMUser", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.BanIdentifier", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.Ban", "Ban")
                        .WithMany("BanIdentifiers")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.FaceFeature", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.Outfit", "Outfit")
                        .WithMany("FaceFeatures")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.HeadBlend", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.Outfit", "Outfit")
                        .WithOne("HeadBlend")
                        .HasForeignKey("LSDM.Domain.Entities.HeadBlend", "OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.HeadOverlay", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.Outfit", "Outfit")
                        .WithMany("HeadOverlays")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.LSDMUser", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.ServerRole", "ServerRole")
                        .WithMany("Users")
                        .HasForeignKey("ServerRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerRole");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.Outfit", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.LSDMUser", "User")
                        .WithOne("Outfit")
                        .HasForeignKey("LSDM.Domain.Entities.Outfit", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.OutfitComponent", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.Outfit", "Outfit")
                        .WithMany("Components")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.OutfitProp", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.Outfit", "Outfit")
                        .WithMany("Props")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.LSDMUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.LSDMUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LSDM.Domain.Entities.LSDMUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LSDM.Domain.Entities.LSDMUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LSDM.Domain.Entities.Ban", b =>
                {
                    b.Navigation("BanIdentifiers");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.LSDMUser", b =>
                {
                    b.Navigation("AssignedBans");

                    b.Navigation("Bans");

                    b.Navigation("Outfit")
                        .IsRequired();
                });

            modelBuilder.Entity("LSDM.Domain.Entities.Outfit", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("FaceFeatures");

                    b.Navigation("HeadBlend")
                        .IsRequired();

                    b.Navigation("HeadOverlays");

                    b.Navigation("Props");
                });

            modelBuilder.Entity("LSDM.Domain.Entities.ServerRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
